name: Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - uses: microsoft/setup-msbuild@v2

    - run: dotnet restore DesktopBridgeSample.sln

    - run: dotnet publish DesktopBridgeSample.Forms\DesktopBridgeSample.Forms.csproj -a x86 -c Release --no-restore --self-contained -p:EnableCompressionInSingleFile=$env:EnableCompressionInSingleFile -p:IncludeNativeLibrariesForSelfExtract=$env:IncludeNativeLibrariesForSelfExtract -p:PublishSingleFile=$env:PublishSingleFile
      env:
        EnableCompressionInSingleFile: true
        IncludeNativeLibrariesForSelfExtract: true
        PublishSingleFile: true

    - run: msbuild DesktopBridgeSample.Package\DesktopBridgeSample.Package.wapproj /v:m /p:AppxBundle=$env:AppxBundle /p:Configuration=$env:Configuration /p:Platform=$env:Platform /p:UapAppxPackageBuildMode=$env:UapAppxPackageBuildMode
      env:
        AppxBundle: Never
        Configuration: Release
        Platform: x86
        UapAppxPackageBuildMode: SideloadOnly

    - uses: actions/upload-artifact@v4
      with:
        name: AppPackages
        path: DesktopBridgeSample.Package\AppPackages
